quarkus.http.port=8080

realworld.jwt.issuer=https://realworld.local
realworld.jwt.ttl=PT2M
realworld.jwt.secret=${REALWORLD_JWT_SECRET:change-me-production-secret-with-at-least-32-characters}
quarkus.http.auth.proactive=false
%dev.realworld.jwt.secret=dev-demo-secret-with-at-least-32-characters
%test.realworld.jwt.secret=test-demo-secret-with-at-least-32-characters

quarkus.mongodb.database=realworld
%dev.quarkus.mongodb.database=realworld_dev
%test.quarkus.mongodb.database=realworld_test
