quarkus.http.port=8080

jnosql.document.database=realworld

smallrye.jwt.new-token.lifespan=300
smallrye.jwt.new-token.issuer=realworld-api
mp.jwt.token.header=Authorization
mp.jwt.token.prefix=Bearer
mp.jwt.verify.issuer=realworld-api
mp.jwt.verify.token.age=300

%dev.mp.jwt.verify.publickey.location=publicKey.pem
%dev.smallrye.jwt.sign.key.location=privateKey.pem
%dev.quarkus.native.resources.includes=publicKey.pem