quarkus.http.port=8080
smallrye.jwt.new-token.lifespan=300
smallrye.jwt.new-token.issuer=realworld-api
mp.jwt.token.header=Authorization
mp.jwt.token.prefix=Bearer
mp.jwt.verify.issuer=realworld-api
mp.jwt.verify.token.age=300

jnosql.document.database=realworld
%test.quarkus.mongodb.health.enabled=false
